### ISSUE TITLE
KSPWheel and Foundaries Testing 0.9.3.12

### ISSUE THREAD

**Issue by rasta013** [shadowmage45/KerbalFoundries2#10] opened 2017-02-21 20:29 UTC
Feedback on issues found during testing:
I got to work on the KF Medium and Large wheels this morning since my time was short and those are easy to test.  They are looking wonderful.  I see no major problems with them at all and the performance of them is excellent.  Mechanics, configuration settings/changes as well as sound and visual effects all appear to be in working order.  Rescales are probably the kookiest thing going on right now across the board.

Things I've found so far...

 - ~~Quirk with the sliders for Spring Rating and Damp Ratio while in flight mode
Even if you grab the little white slider on the bar you cannot move it by more than one click at a time.  E.G. Spring ratio defaults to 0.65.  If I want to change that 0.50 I have to click on and drag the slider 3 times.  The other fields for brake and motor limits slide fully as normal.  Alternatively, you can click somewhere on the bars and move it by large jumps but it's not a precise setting.  All of this was only observed during flight.  While in the editor, the sliders work as normal and move freely.  This behavior may be intended since these two settings are so critical to wheel/track setup but figured I'd mention it in case it wasn't.~~  Fixed

- ~~In the editor on rescaled 2x KF Medium Wheel
For any loaded vessel with rescaled wheels the only way to get the Max Drive Speed to update after changing it is to exit the editor and go back.  The initial value after loading is proper.  This behavior only shows up when trying to change the gear ratio on a loaded vessel.  Oddly though, while building using rescaled wheels, it updates as it should.  Standard 1x non-scaled worked as intended and even on loaded vessels the speed field would update as the ratio was changed.  I only verified this on the medium wheel so far but will check for that behavior on other rescales.~~  Fixed

- RE: Rescaled Wheels
Weirdness in a few areas...
![screenshot1](https://cloud.githubusercontent.com/assets/12317827/23186359/7cf10e74-f84c-11e6-92c9-52be433eaa00.png)
As you can see, wheels are totally submerged beneath the water.  This was only happening on the rescale (2x).  All my testing on this issue was done using the KF Medium Wheel.  If you also notice, I'm not getting any propulsion in the slightest out of them either.  I can turn in the water by accelerating and then turning as normal but it never goes forward - only left/right in a spin.  After about 5 minutes suddenly the left rear wheel menu showed failure time climbing for about 3-4 seconds and then ALL wheels broke.  Not just the left rear.  I didn't get a screenshot of it in process because I was literally typing in this window when it happened. LOL.

**Comment by shadowmage45** [comment] 2017-02-22 01:04
Scale / Damper sliders -- unintended side-effect of an intentional implementation detail with slider value updating.  I had noticed it on some sliders in SSTU as well, so it must be something in some of the code that I've re-used between the two.  Now that I know where to look, I should be able to gather more info on this one.

Max Speed updating in editor for rescaled parts -- investigating this now, pretty sure I have it fixed with some other cleanup I was doing in the motor module.  Will update when I know more info.  Edit:  Was actually caused by three different things that would manifest in specific situations.  Should all be fixed now, available in the .dll from the KSPWheels dev branch.

No water-output on wheels -- yep, fully submerged wheels will not output any force.  You are probably able to still spin because of the reaction wheels in the craft.  You would need to mount the wheels higher so that they are at least partially above water in order to get any force output from them.  If you can duplicate the wheel breakage issue, please let me know.

Thanks for the notes so far, should be able to get the first two cleaned up shortly.

**Comment by rasta013** [comment] 2017-02-22 01:43
Absolutely - I'll have more time tomorrow to gather better info on that water issue and to start really diving into the ALG pieces next.

**Comment by rasta013** [comment] 2017-02-22 06:34
A quick question re: water behavior...for the purposes of determining where the wheels should be at in relation to the water surface is the lowest part of the craft used as the reference point?  
![screenshot2](https://cloud.githubusercontent.com/assets/12317827/23199808/56398302-f896-11e6-8b63-adea540e5ff2.png)
I ask because no matter what I did with the wheels on this craft I could never get them to float.  They submerged every single time no matter what speed I hit the water or what settings I was using on the suspension.  I only got to play around with this idea for about 20 minutes but thought I'd ask this question before I dig harder on it tomorrow...

**Comment by shadowmage45** [comment] 2017-02-22 07:00
Water propulsion considers the position of the wheel mesh at max droop.  This is somewhat lower than what is shown on the wheels in the editor.

Its not going to float on the wheels, at least not intentionally; none of this code effects floating, that is all handled by stock code.  You need to position the wheels in such a way that they are only partially submerged while the vehicle is floating on the hull.

**Comment by shadowmage45** [comment] 2017-02-22 23:55
Here is how wheels need to be positioned in order to get water-propulsion to work.  Note that when it is floating in the water, part of the visible wheel mesh is above the surface, but is floating mostly on the buoyancy of the hull.

Editor:
![screenshot10](https://cloud.githubusercontent.com/assets/1503399/23238531/95354a4e-f91f-11e6-8f09-2c5d621f29d8.png)

Runway:
![screenshot7](https://cloud.githubusercontent.com/assets/1503399/23238533/97074304-f91f-11e6-89dd-816b9b92bd5d.png)

In Water:
![screenshot8](https://cloud.githubusercontent.com/assets/1503399/23238535/99580b5c-f91f-11e6-859e-bd3822c7ae66.png)

**Comment by rasta013** [comment] 2017-02-23 04:00
Got it. That tells me absolutely everything I needed to know about it.  (mostly avoided the water tonight)

On a quick side note...been doing spot tests on all the wheels and tracks using default config on super light vehicles and haven't seen any abnormal behavior in ground ops in these quick passes.  ALG will be getting attacked tomorrow as I ran outta time tonight.  Scaling, as already mentioned by you, does seem to cause all kinds of little quirks across the parts in these quick tests looking at top level behavior thus the general trend continues.

**Comment by rasta013** [comment] 2017-02-24 05:04
Updated to the latest dev version with the drag cube commits...working on testing ALG and that specific aspect added tonight immediately...

**Comment by shadowmage45** [comment] 2017-02-24 05:33
Sadly the drag cube stuff isn't quite working out in the dev versions (it doesn't crash or anything, just not quite working).

I'm working on tracking it down now, but unsure as to what the cause could be.  The drag cubes are certainly updating (can see them change on the drag debug info on the part menu), but the resultant drag output is not much different (it only decreases by ~25% while retracted).  Will have to spend a bit of time on that one tomorrow/over the weekend, as its a pretty big deal to get working properly (draggy landing gear = no good at all).

The rest of the ALG stuff should still be testable though -- wheel and strut angling, wheel-ground-alignment button, strut-extension / length adjustments, updated rigging, etc.

**Comment by rasta013** [comment] 2017-02-24 06:00
LOL - ok added my comments to the KSPWheel bug tracker about the drag cube and I have screenshots but won't clutter the thread with them.

As for other behavior...looking fantastic actually.  On both versions of the small gear as well as the medium gear all the little tweaks, bells and whistles are working fine.  Wheel alignment, extension adjustments, new rigging (beautiful btw) is great and the sliders all seem to be working properly.  Still haven't made sure of the large gear - need my large aircraft - but I'm not worried at all.

~~One suggestion I had which you may already be doing - the new version of the small gear is named the exact same thing as the other version (straight vs side mount).  Is there a way to differentiate the names?  Obviously not a major issue but clarity is always good if possible...~~  Fixed

**Comment by shadowmage45** [comment] 2017-02-24 18:04
Naming -- yep, should be fixable.  They already have unique part-ids (the important part, the one that would cause problems); fixing up the display name is simple enough to do.

Drag cube stuff -- I'm at a bit of a loss as to why it is not working as it should.  Well, its technically working, but the drag is not being reduced as much as it logically should be.  I have a few ideas to investigate a bit further as to why it isn't working, and a few ideas on how to fix it, sadly none of them are easy or fast (require quite major changes to the low-level loading code, which is likely to cause all sorts of other problems in the long run).

**Closed as completed** 2017-03-20 15:37 UTC
